server:
  port: 8002
spring:
  application:
    name: dynamic-datasource-jpa
  datasource:
    primary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/test?serverTimeZone=Asia/shanghai&useSSL=false
      username: root
      password: root
    secondary:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://localhost:3306/clouddb?serverTimeZone=Asia/shanghai&useSSL=false
      username: root
      password: root
  jpa:
    show-sql: true
    database: mysql